version: '3'
services:
  web:
    image: nginx:latest
    container_name: sample_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf